[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/server/functions"

# Essential security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "img-src 'self' https: data:"

# API routes - no caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
    Netlify-CDN-Cache-Control = "no-store"

# Force HTTPS (recommended)
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true